# -*- coding: utf-8 -*-
"""player_survival_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RHcvFSdqE8mZzCwvyg3HyNqDZthbuAWR
"""

updatedFinalDataset=pd.read_csv("finalDataset.csv")
float_df = updatedFinalDataset["Pressure Array"].apply(lambda x: [float(el) for el in x.strip("[]").split(",")])
updatedFinalDataset["Pressure Array"] = float_df
newScout=pd.merge(scout, plays, on=['gameId','playId'])
allPlayers=pd.merge(newScout, passingRatesWithExpectation, on=['gameId','playId'])
pass_rushers=scout.loc[scout['pff_role']=="Pass Rush"]
pass_rushers['nflIdList']=pass_rushers['nflId'].apply(funcList)
pass_rushers['positions']=pass_rushers['pff_positionLinedUp'].apply(funcList)
pass_rushers['count']=1
pass_rushers
bingpot1=pd.DataFrame(pass_rushers.groupby(['gameId','playId'])['count'].sum())
bingpot2=pd.DataFrame(pass_rushers.groupby(['gameId','playId'])['nflIdList'].sum())
bingpot3=pd.DataFrame(pass_rushers.groupby(['gameId','playId'])['positions'].sum())
bingpot=pd.merge(bingpot1, bingpot2, on = ['gameId','playId'])
bingpot=pd.merge(bingpot, bingpot3, on = ['gameId','playId'])
passRushers=pd.merge(updatedFinalDataset, bingpot,on=['gameId','playId'])
fourManPassRush=passRushers.loc[passRushers['count']==4]
fourManPassRush['lGame']=fourManPassRush['gameId'].apply(funcList)
fourManPassRush['lPlay']=fourManPassRush['playId'].apply(funcList)
fourManPassRush['tup']=fourManPassRush['lGame']+fourManPassRush['lPlay']
fourManPassRush

def create_survival_analysis(df):
    frames = []
    pressure_values = []

    for _, row in df.iterrows():
        cur_frames = []
        cur_pressure_values = []
        for frame in range(35):
            if not math.isnan(row[frame]):
                cur_frames.append(frame)
                cur_pressure_values.append(row[frame])
        pressure_values.extend(cur_pressure_values)
        frames.extend(cur_frames)

    survival_values = pd.DataFrame({'Frame': frames, 'Pressure': pressure_values})
    survival_values['g90'] = np.where(survival_values['Pressure'] >= 0.915, True, False)

    pred_frame, pred_survival_prob = kaplan_meier_estimator(survival_values["g90"], survival_values["Frame"])
    plt.plot(pred_frame, pred_survival_prob)
    plt.ylabel("Survival Probability")
    plt.xlabel("Elapsed Frames")
    plt.show()
    return [pred_frame, pred_survival_prob]

dictPlayer={}
onField=[]
dictTeam={}
teams = fourManPassRush["defensiveTeam"].unique()
for team in teams:
  dictTeam={}
  team_df = fourManPassRush.loc[fourManPassRush["defensiveTeam"]==team]
  for index, row in team_df.iterrows():
    for i in row['nflIdList']:
      if i in dictTeam.keys():
        dictTeam[i].append([row['gameId'],row['playId']])
      else:
        dictTeam[i]=[[row['gameId'],row['playId']]]
  for i in dictTeam:
    if len(dictTeam[i])>=35:
      try:
        lst=[]
        onField=team_df.loc[team_df['tup'].isin(dictTeam[i])]
        offField=team_df.loc[~(team_df['tup'].isin(dictTeam[i]))]
        for index, row in onField.iterrows():
          lst.append(row['Pressure Array'])
        lst_df = pd.DataFrame(lst)
        survival_curve = create_survival_analysis(lst_df)
        survival_curve [0] = 0.1 * survival_curve[0]
        on_field_survival_auc = integrate.simpson(survival_curve[1], survival_curve[0], axis=0)
        lst=[]
        for index, row in offField.iterrows():
          lst.append(row['Pressure Array'])
        lst_df = pd.DataFrame(lst)
        survival_curve = create_survival_analysis(lst_df)
        survival_curve [0] = 0.1 * survival_curve[0]
        off_field_survival_auc = integrate.simpson(survival_curve[1], survival_curve[0], axis=0)
        dictPlayer[i]=[on_field_survival_auc,off_field_survival_auc]
      except:
        pass

listSurplusValue=[]
for i in dictPlayer:
  listSurplusValue.append([i,dictPlayer[i][1]-dictPlayer[i][0], dictPlayer[i][0], dictPlayer[i][1]])

playerSurplusValue=pd.DataFrame(Sort(listSurplusValue))
playerSurplusValue.columns=['nflId','surplusValue','On-Field Expectancy (35 Frames)','Off-Field Expectancy (35 Frames)']
playerSurplusTable=pd.merge(playerSurplusValue, players, on='nflId')
orderedRankings=playerSurplusTable.sort_values('surplusValue', ascending=False)
defensiveEndRankings=orderedRankings.loc[orderedRankings['officialPosition']=="DE"]
OLBRankings=orderedRankings.loc[orderedRankings['officialPosition']=="OLB"]
NTRankings=orderedRankings.loc[orderedRankings['officialPosition']=="NT"]
DTRankings=orderedRankings.loc[orderedRankings['officialPosition']=="DT"]

def funcList(val):
  return [val]